from fastapi import FastAPI
from pydantic import BaseModel, Field

from src.rag.pipeline import generate_answer

app = FastAPI(
    title="Northstar RAG API",
    description="POC QnA agent",
    version="0.1.0",
)


class ChatRequest(BaseModel):
    question: str = Field(
        min_length=1,
        max_length=300,
        description="Question to the Northstar agent.",
        examples=["What does Northstar do?"],
    )


class ChatResponse(BaseModel):
    answer: str = Field(
        description="Answer generated by the agent from retrieved context.",
        examples=["Northstar Culinary Technologies provides..."],
    )


@app.post(
    "/chat",
    response_model=ChatResponse,
    summary="Ask the Northstar agent",
    description="Returns an answer based on context retrieved.",
    tags=["chat"],
)
def chat(request: ChatRequest) -> ChatResponse:
    result = generate_answer(request.question)
    return ChatResponse(answer=result["answer"])
